document.querySelector(`.link-section-company-par-Terms-Condition`).addEventListener('click',()=>{
    let hi=document.querySelector('.about-grid')

    
    let bro = document.querySelector('.text-a2d-2 h1');
    bro.textContent = "Terms & Conditions";

let Terms=`<div class="Terms">
                    <p>Thank you for choosing A2D PC Factory. Our commitment is to deliver high-performance custom PC solutions that empower your creativity, productivity, and enjoyment. By accessing, browsing, or using our website, placing an order, or engaging with our services, you acknowledge that you have read, understood, and agreed to be legally bound by these Terms. Please read them carefully.</p>
                    <div class="innner-terms"><h2>1. General Terms</h2><p>1. Acceptance of Terms: By accessing our website and purchasing our products, you agree to comply with and be bound by these terms and conditions.
                                                <br>2. Modifications: We reserve the right to change or modify these terms at any time. If we make any material changes, we will notify you promptly. Your continued use of our website following any changes indicates your acceptance of the new terms</p>
                    </div>
                    
                    <div class="innner-terms"><h2>2. Products and Services</h2><p>1. Product Description: We strive to provide accurate descriptions and images of our products. Minor variations in product color, size, or design due to technical limitations are not considered defects and we do not warrant that the product descriptions or other content on our website are error-free, complete, or current.
                                               <br> 2. Customization: Our PCs are customizable to meet your specific needs. Please ensure that your customization choices are accurate, as we cannot be held responsible for errors in the configuration specified by you. Any changes after the confirmation of your order must be reported to us within 24 hrs. Once customization details are confirmed, accepting or declining modifications will be allowed at the discretion of A2D PC Factory and changes to the order may incur additional charges.</p>
                    </div>

                    <div class="innner-terms"><h2>3. Ordering and Payment</h2><p>1. Order Process: By placing an order, you agree to purchase a product according to these terms. All orders are subject to availability and acceptance.
                                                <br>2. Payment: Payment must be made in full before dispatching any products. We accept various payment methods, like UPI, Net Banking, EMI Options, Cash and any other Payment methods if specifically requested by the User (only if it's feasible at our side). Further details will be provided during the order process.
                                                <br> 3. Order Confirmation: To initiate an order placement, a minimum payment of 20% of the total cost is required. Once you place an order, you will receive an order confirmation on the website, Whatsapp, SMS and through Email. This does not mean that your order has been accepted. We reserve the sole discretion to decline or cancel any order at any time, should valid reasons arise. The 20% minimum payment is only refundable within the first 24 hours after the order is placed. After this period, the payment will be considered non-refundable.</p></div>

                    <div class="innner-terms"><h2>4. Building and Testing</h2><p>1. Post-Order Confirmation: Upon order placement, please anticipate a timeframe of approximately 3 to 7 working days for the completion of both the build and testing phases. This duration excludes packing and delivery times. Please note that the availability of components may influence the delivery date.
                                                <br>2. Building Phase: The build process commences once all necessary components are confirmed available. However, in the event of unforeseen circumstances causing delays in component arrival, the build will be temporarily halted, and the customer will be promptly notified of the situation. Prompt notifications will be provided throughout all phases of your order, including Order Placement, Under Build and Testing, Ready to Dispatch, Dispatched, and Delivered. Real-time updates will be reflected on the website, and you will also receive updates through other channels such as WhatsApp, SMS, email, or via call.
                                                <br>3. Testing Phase: Following completion of the build, the PC undergoes a rigorous 48-hour testing phase to ensure quality standards are met. Only upon successful completion of the quality check will the PC proceed to the shipping stage. In the event of power disruptions or in any other unexpected scenarios causing delays during testing, the process will be temporarily paused, and customers will be duly informed of any such occurrences. If the system fails quality checks, additional time may be required for troubleshooting and rectification. Delays may also occur under certain circumstances, such as a high volume of orders or other unexpected hurdles. Upon successful completion of the testing phase, customers will be provided with the test results, including all necessary checks for validation, such as benchmarks and performance metrics.</p></div>

                    <div class="innner-terms"><h2>5. Shipping and Delivery</h2><p>1.Shipping Policy: Shipping is done free of cost within India and estimated delivery time is entirely at the discretion of the carrier and is subject to their updates. Delivery times are estimated and not guaranteed. Please note that shipping procedures will commence only after full payment has been completed. If the recipient is unavailable and the product returns back to us , extra shipping cost will be applicable. A2D PC Factory is not responsible for any delays caused by suppliers, logistics, or force majeure events. Force majeure includes, but is not limited to, acts of God, natural disasters , epidemics or pandemics, acts of war, civil unrest, terrorism, labor strikes, governmental actions, embargoes, or any other unforeseen circumstances beyond A2D PC Factory's control that may hinder or delay the production, shipping, or delivery process. In such cases, customers will be promptly informed, and all reasonable efforts will be made to minimize the impact of such delays.
                                                <br>2.Order Tracking: Once your order is shipped, you will receive a tracking number. You can use this number to track your order's progress. The tracking number and the delivery partner's name will be communicated to you via our communication channels, such as WhatsApp, SMS, email, or call, and will also be reflected on the website for your convenience. You can use this information to track your order's progress.
                                                <br> 3.Risk of Loss or Damage: All purchases are made pursuant to a shipment contract. A2D PC Factory ensures that all products are securely packed using ultra-durable 3 Layer Package to minimize the risk of damage during transit. However, if there is any damage during transit, A2D PC Factory will not be held responsible. We will, however, support you in raising a complaint with the relevant shipping partner to address the issue. In the event of loss or theft during transit, A2D PC Factory will assist by coordinating with the delivery partners to help resolve the issue and facilitate the recovery or replacement of the product, subject to the delivery partner's policies and procedures.</p></div>

                    <div class="innner-terms"><h2>6. Returns and Refunds</h2><p>1.Returns: We do not accept returns for refunds or exchanges once the product has been delivered. Please note that the warranty period begins immediately after the e-invoice is issued, and as a result, returns are no longer available. However, in the unlikely event that a wrong product has been delivered to you or there is a mismatch in the components during the build, we will address the issue. In such cases, on-site service will be provided if feasible. If on-site service is not possible, the customer will be requested to ship the PC back to us, and A2D PC Factory will bear the shipping charges.
                                                <br>2.Refunds: Refunds can be requested within 24 hours of the initial payment; however, they will only be processed if a valid and acceptable reason is provided. Please note that requests made after this timeframe or without a justifiable reason will not be eligible for consideration. Refunds for valid requests will be processed within 7–14 business days after approval.</p></div>

                    <div class="innner-terms"><h2>7. Warranty and Support</h2><p>1.General Warranty: While we do not offer a comprehensive warranty for our products, the brand's warranty of the respective component will apply to all items. Details regarding the brand's warranty can be accessed on their official website. However, we do assist in facilitating the warranty claim process for products covered by the respective brand's warranty. A2D PC Factory facilitates the warranty process as a goodwill service and does not guarantee outcomes.
                                                <br>2.Customer Support: Our customer support team is available to assist you with any issues or questions you may have. Contact details and support hours are listed on our website.
                                                <br>3. A2D PC Factory Warranty: Every A2D PC Factory-built computer comes with a complimentary service for three months. On-site services can be availed for metro cities such as Chennai or Coimbatore (Subject to availability). In case of non availability of On-site service , customers can ship their PC to us to claim our A2D PC Factory warranty and we will bear the shipping for the three-month time frame. After the complimentary period, on-site service will be chargeable and subject to availability.
                                                <br>4. A2D PC Factory Service : Following the three-month complimentary service period, customers who purchase our products can access our services at any time. Please note that services availed will incur conveyance and component charges.</p></div>

                    <div class="innner-terms"><h2>8.Limitation of Liability</h2><p>1. Disclaimer of Warranties: To the fullest extent permitted by law, A2D PC Factory disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.
                                                <br>2. Limitation of Liability: A2D PC Factory shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with the use of our products or services.</p></div>

                    <div class="innner-terms"><h2>9. Intellectual Property & Disclaimer</h2><p>1. Ownership: All content on our website, including text, graphics, logos, images, and software, is the property of A2D PC Factory or its content suppliers and is protected by intellectual property laws. All trademarks, logos, and brand names used on this website are the property of their respective owners and are used solely for identification and informational purposes. A2D PC Factory is not affiliated with or endorsed by any of these brands.
                                                <br> 2.Use of Content: You may not use, reproduce, distribute, or display any content from our website without our prior written consent.</p></div>

                    <div class="innner-terms"><h2>10. Privacy</h2><p>1.Privacy Policy: We value your privacy and are committed to protecting your personal information. Our [privacy policy], available on our website, outlines how we collect, use, and safeguard your data.</p></div>

                    <div class="innner-terms"><h2>11. Governing Law</h2><p>1.Jurisdiction: These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction in which A2D PC Factory operates. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in that jurisdiction.</p></div>

                    <div class="innner-terms"><h2>12. Contact Information</h2><p>1. Customer Support: For any questions or concerns regarding these terms and conditions, please contact our customer support team at support@a2dpcfactory.com or call us at +91 90253 80083, +91 94457 47768.</p></div>

            </div>`

            let termsStyle=document.querySelector('.about-grid')
            let aboutHeight=document.querySelector('.about-section')
            termsStyle.style.margin="0 10% 0 10%";
            termsStyle.style.height="100%"
            termsStyle.style.display="block"

            hi.innerHTML=Terms
           document.querySelector(".a2d-h2").scrollIntoView({behavior: "smooth"});


})